Build the cachi2 image in GH actions with podman
After building the cachi2 image with buildah, `podman run` somehow stops
working.

```
$ podman run -t cachi2:${{ github.sha }} --version
...
time="2023-05-31T11:24:06Z" level=warning msg="Failed to add conmon to cgroupfs sandbox cgroup: creating cgroup path /libpod_parent/conmon: write /sys/fs/cgroup/cgroup.subtree_control: operation not supported"
Error: OCI runtime error: crun: the requested cgroup controller `pids` is not available
```

This doesn't happen when building the image with podman. It also doesn't
happen when building a different image with buildah. It is the specific
combination of `buildah bud` + the cachi2 Containerfile that somehow
breaks podman afterwards.

Use podman build instead of buildah to avoid this issue.

Note: based on further testing, it seems that buildah breaks podman if
the Containerfile has any RUN instruction.

Signed-off-by: Adam Cmiel <acmiel@redhat.com>