Fix sorting and de-duplication of dev dependencies
Currently, downloading the same dependency as both dev and non-dev
triggers a conflict.

```
pydantic.error_wrappers.ValidationError: 1 validation error for Package
dependencies
  conflict by ('pip', 'packaging', '22.0'):
    type='pip' name='packaging' version='22.0' dev=False
    X
    type='pip' name='packaging' version='22.0' dev=True
```

Do not raise a conflict, report both.

When sorting, consider 'dev' the second most important attribute after
'type'. Non-dev dependencies come first, then the dev dependencies.

Signed-off-by: Adam Cmiel <acmiel@redhat.com>