run_cmd: execute programs by their absolute path
To avoid complex and platform-dependent interaction of subprocess.run
with the 'env' parameter (see the previous commit), execute programs by
abspath so that subprocess.run doesn't have to look for them in PATH.

To get the abspath, use shutil.which(), which also looks for the program
in PATH but doesn't have the gotchas that subprocess.run does.

If the program is not found, raise a friendlier error than the default
FileNotFoundError: [Errno 2] No such file or directory: 'foo'

Signed-off-by: Adam Cmiel <acmiel@redhat.com>