CI: enable pip_custom_index integration test in CI
As a prerequisite, bump the version of the fedora container that
executes integration tests. The url -> filename detection in curl 7.85.0
(installed in the fedora:37 container) does not handle URL fragments and
therefore does not create the files for pypiserver correctly. The issue
was fixed in the very next curl version [1].

The version bump of the fedora container also required adding a volume
mount for /var/lib/containers - otherwise, the tests failed with

    Error: configure storage: 'overlay' is not supported over overlayfs,
    a mount_program is required: backing file system is unsupported for
    this graph driver

[1]: https://github.com/curl/curl/issues/12478

Signed-off-by: Adam Cmiel <acmiel@redhat.com>